Update batterycontrol

diff --git a/batterycontrol b/batterycontrol
--- a/batterycontrol
+++ b/batterycontrol
@@ -192,11 +192,11 @@ start_monitoring_loop() {
         if (( now - last_reload_time >= 30 )); then
             load_config
             last_reload_time=$now
-            if read -r BATTERY_CHARGE < "$BATTERY_PATH"; then
-                echo "${GREEN}$(date '+%Y-%m-%d %H:%M:%S') - Battery: ${BATTERY_CHARGE}% -> Charge Limit: ${CHARGE_MAX}%${RESET}" >> "$LOG_FILE"
-            else
-                echo "Failed to read $BATTERY_PATH" >&2
-            fi
+            #if read -r BATTERY_CHARGE < "$BATTERY_PATH"; then
+            #    echo "${GREEN}$(date '+%Y-%m-%d %H:%M:%S') - Battery: ${BATTERY_CHARGE}% -> Charge Limit: ${CHARGE_MAX}%${RESET}" >> "$LOG_FILE"
+            #else
+            #    echo "Failed to read $BATTERY_PATH" >&2
+            #fi
         fi
 
        if [ -f "$BATTERY_PATH" ]; then
