Update batterycontrol

diff --git a/batterycontrol b/batterycontrol
--- a/batterycontrol
+++ b/batterycontrol
@@ -20,6 +20,13 @@ LOG_FILE="/var/log/batterycontrol.log"
 timestamp=$(printf '%(%Y-%m-%d %H:%M:%S)T\n' -1)
 CONF_SOURCE="$INSTALL_DIR/batterycontrol.conf"
 CONF_TARGET="/etc/init/batterycontrol.conf"
+
+if [ ! -f /bin/ectool ]; then
+    echo "${RED}ectool not found. Exiting.${RESET}"
+    sleep 3
+    exit 1
+fi
+
 wait_for_config() {
     local config_dir="/home/chronos/user/MyFiles/Downloads/ChromeOS_PowerControl_Config"
     local max_wait=300
