Update batterycontrol

diff --git a/batterycontrol b/batterycontrol
--- a/batterycontrol
+++ b/batterycontrol
@@ -126,14 +126,19 @@ echo ""
         if [ "$active_port" != "-1" ]; then
 
 echo "Active USB-PD Charger Port: $active_port (CROS_USBPD_CHARGER$active_port) ${RESET}"
-        else
-echo "Active USB-PD Charger Port: None detected ${RESET}"
-echo ""
 sudo ectool usbpdpower 2>/dev/null || echo "Failed to run ectool usbpdpower (is ectool installed and available?)"
 echo
 sudo ectool battery 2>/dev/null || echo "Failed to run ectool battery (is ectool installed and available?)"
 echo "═════════════════════════════════════════════════════════════════════════════"
-        echo "${RESET}"
+echo "${RESET}"
+        else
+echo "Active USB-PD Charger Port: None detected ${RESET}"
+sudo ectool usbpdpower 2>/dev/null || echo "Failed to run ectool usbpdpower (is ectool installed and available?)"
+echo
+sudo ectool battery 2>/dev/null || echo "Failed to run ectool battery (is ectool installed and available?)"
+echo "═════════════════════════════════════════════════════════════════════════════"
+echo "${RESET}"
+
     fi
 }
 
