Update fancontrol

diff --git a/fancontrol b/fancontrol
--- a/fancontrol
+++ b/fancontrol
@@ -21,6 +21,13 @@ MONITOR_PID_FILE="$INSTALL_DIR/.fancontrol_monitor.pid"
 timestamp=$(printf '%(%Y-%m-%d %H:%M:%S)T\n' -1)
 CONF_SOURCE="$INSTALL_DIR/fancontrol.conf"
 CONF_TARGET="/etc/init/fancontrol.conf"
+
+if [ ! -f /bin/ectool ]; then
+    echo "${RED}ectool not found. Exiting.${RESET}"
+    sleep 3
+    exit 1
+fi
+
 wait_for_config() {
     local config_dir="/home/chronos/user/MyFiles/Downloads/ChromeOS_PowerControl_Config"
     local max_wait=300
