Update powercontrol

diff --git a/powercontrol b/powercontrol
--- a/powercontrol
+++ b/powercontrol
@@ -2,7 +2,14 @@
 
 INSTALL_DIR="$INSTALL_DIR/ChromeOS_PowerControl"
 USER_HOME="/home/chronos"
-CONFIG_FILE="$INSTALL_DIR/.powercontrol_config"
+CONFIG_FILE="/usr/local/bin/ChromeOS_PowerControl/config.sh"
+
+if [ -f "$CONFIG_FILE" ]; then
+    source "$CONFIG_FILE"
+else
+    echo "Missing configuration file: $CONFIG_FILE"
+    exit 1
+fi
 RUN_FLAG="$INSTALL_DIR/.powercontrol_enabled"
 PID_FILE="$INSTALL_DIR/.powercontrol_pid"
 NO_TURBO_BACKUP="$INSTALL_DIR/.no_turbo_backup"
