Update powercontrol
base 10 version support

diff --git a/powercontrol b/powercontrol
--- a/powercontrol
+++ b/powercontrol
@@ -738,30 +738,31 @@ case "$1" in
     fi
     ;;
        version)
-            if [[ -f "$VERSION_FILE" ]]; then
-            CURRENT_VER=$(cat "$INSTALL_DIR/version")
-            CURRENT_VER_NO=$(echo "$CURRENT_VER" | sed -e 's/VERSION=//' -e 's/"//g' -e 's/\.//g')
-        
-            LATEST_VER=$(curl -Ls https://raw.githubusercontent.com/shadowed1/ChromeOS_PowerControl/main/version)
-            LATEST_VER_NO=$(echo "$LATEST_VER" | sed -e 's/VERSION=//' -e 's/"//g' -e 's/\.//g')
-        
-            if [[ "$CURRENT_VER_NO" -lt "$LATEST_VER_NO" ]]; then
-                echo "${CYAN}You're using $CURRENT_VER which is NOT the latest version.${RESET}"
-                read -rp "Would you like to 'reinstall' to get $LATEST_VER ? (Y/n): " choice
-                if [[ "$choice" =~ ^[Yy]$ ]]; then
-                    echo "${CYAN}Reinstalling!${RESET}"
-                    exec sudo powercontrol reinstall
-                else
-                    echo "${YELLOW}Skipping reinstall.${RESET}"
-                fi
+    if [[ -f "$VERSION_FILE" ]]; then
+        CURRENT_VER=$(cat "$INSTALL_DIR/version")
+        CURRENT_VER_NO=$(echo "$CURRENT_VER" | sed -e 's/VERSION=//' -e 's/"//g' -e 's/\.//g' -e 's/^0*//')
+
+        LATEST_VER=$(curl -Ls https://raw.githubusercontent.com/shadowed1/ChromeOS_PowerControl/main/version)
+        LATEST_VER_NO=$(echo "$LATEST_VER" | sed -e 's/VERSION=//' -e 's/"//g' -e 's/\.//g' -e 's/^0*//')
+
+        if (( 10#$CURRENT_VER_NO < 10#$LATEST_VER_NO )); then
+            echo "${CYAN}You're using $CURRENT_VER which is NOT the latest version.${RESET}"
+            read -rp "Would you like to 'reinstall' to get $LATEST_VER ? (Y/n): " choice
+            if [[ "$choice" =~ ^[Yy]$ ]]; then
+                echo "${CYAN}Reinstalling!${RESET}"
+                exec sudo powercontrol reinstall
             else
-                echo "${GREEN}You're using $CURRENT_VER which is up-to-date, so you're good.${RESET}"
+                echo "${YELLOW}Skipping reinstall.${RESET}"
             fi
         else
-            echo "${RED}Version file not found.${RESET}"
-            exit 1
+            echo "${GREEN}You're using $CURRENT_VER which is up-to-date, so you're good.${RESET}"
         fi
-    ;;
+    else
+        echo "${RED}Version file not found.${RESET}"
+        exit 1
+    fi
+;;
+
     reinstall)
     echo "Downloading to:${CYAN} /home/chronos/ChromeOS_PowerControl_Installer.sh $RESET"
     bash <(curl -s "https://raw.githubusercontent.com/shadowed1/ChromeOS_PowerControl/main/ChromeOS_PowerControl_Downloader.sh?$(date +%s)")
