Update powercontrol

diff --git a/powercontrol b/powercontrol
--- a/powercontrol
+++ b/powercontrol
@@ -67,8 +67,14 @@ save_config() {
 }
 
 get_temp_kelvin() {
-    ectool temps 2 2>/dev/null | grep ' K' | head -n1 | sed -n 's/.* \([0-9]\+\) K.*/\1/p'
+    temp=$(ectool temps 2>/dev/null | grep ' K' | head -n1 | sed -n 's/.* \([0-9]\+\) K.*/\1/p')
+    if [ -z "$temp" ]; then
+        echo "Failed to fetch temperature" >&2
+        return 1
+    fi
+    echo $temp
 }
+
 
 # Set the max performance percentage
 set_max_perf_pct() {
